"""Report Generator — Formats research output into structured Markdown reports."""

import os
import re
from datetime import datetime


def sanitize_filename(topic: str) -> str:
    """Convert a topic string into a safe filename."""
    filename = topic.lower().strip()
    filename = re.sub(r'[^\w\s-]', '', filename)
    filename = re.sub(r'[\s_]+', '_', filename)
    filename = filename[:80].strip('_')
    return filename


def parse_research_sections(raw_output: str) -> dict:
    """Parse the raw agent output into structured sections."""
    sections = {
        "introduction": "",
        "key_findings": "",
        "challenges": "",
        "future_scope": "",
        "conclusion": "",
    }

    section_patterns = {
        "introduction": r"(?:^|\n)\s*(?:##?\s*)?(?:Introduction|INTRODUCTION)[:\s]*(.*?)(?=(?:##?\s*(?:Key\s*Findings|KEY\s*FINDINGS|Challenges|CHALLENGES|Future\s*Scope|FUTURE\s*SCOPE|Conclusion|CONCLUSION))|$)",
        "key_findings": r"(?:^|\n)\s*(?:##?\s*)?(?:Key\s*Findings|KEY\s*FINDINGS|Key\s*Results|Main\s*Findings)[:\s]*(.*?)(?=(?:##?\s*(?:Challenges|CHALLENGES|Future\s*Scope|FUTURE\s*SCOPE|Conclusion|CONCLUSION))|$)",
        "challenges": r"(?:^|\n)\s*(?:##?\s*)?(?:Challenges|CHALLENGES|Limitations|Issues)[:\s]*(.*?)(?=(?:##?\s*(?:Future\s*Scope|FUTURE\s*SCOPE|Conclusion|CONCLUSION))|$)",
        "future_scope": r"(?:^|\n)\s*(?:##?\s*)?(?:Future\s*Scope|FUTURE\s*SCOPE|Future\s*Directions|Outlook)[:\s]*(.*?)(?=(?:##?\s*(?:Conclusion|CONCLUSION))|$)",
        "conclusion": r"(?:^|\n)\s*(?:##?\s*)?(?:Conclusion|CONCLUSION|Summary|Final\s*Thoughts)[:\s]*(.*?)$",
    }

    for section_key, pattern in section_patterns.items():
        match = re.search(pattern, raw_output, re.DOTALL | re.IGNORECASE)
        if match:
            sections[section_key] = match.group(1).strip()

    return sections


def extract_introduction(raw_output: str) -> str:
    """Extract or generate an introduction from the raw output."""
    sections = parse_research_sections(raw_output)
    if sections["introduction"]:
        return sections["introduction"]

    first_paragraphs = raw_output.split("\n\n")[:3]
    return "\n\n".join(p.strip() for p in first_paragraphs if p.strip())


def generate_report(topic: str, raw_output: str, output_dir: str = "outputs") -> str:
    """Generate a structured Markdown report from research output."""
    os.makedirs(output_dir, exist_ok=True)

    sections = parse_research_sections(raw_output)
    date_str = datetime.now().strftime("%B %d, %Y")
    filename = sanitize_filename(topic)
    filepath = os.path.join(output_dir, f"{filename}.md")

    introduction = sections["introduction"] if sections["introduction"] else (
        f"This report presents a comprehensive analysis of **{topic}**, "
        f"covering current developments, key findings, challenges, and future directions. "
        f"The research was conducted using automated web search and knowledge retrieval tools."
    )

    key_findings = sections["key_findings"] if sections["key_findings"] else (
        f"Based on the research conducted, the following key findings were identified:\n\n"
        f"{raw_output[:2000]}"
    )

    challenges = sections["challenges"] if sections["challenges"] else (
        f"Several challenges and limitations were identified during the research on {topic}. "
        f"These include data availability constraints, varying perspectives from different sources, "
        f"and the rapidly evolving nature of the subject matter."
    )

    future_scope = sections["future_scope"] if sections["future_scope"] else (
        f"The field of {topic} continues to evolve rapidly. Future developments are expected "
        f"in areas such as technological advancement, policy frameworks, and broader adoption. "
        f"Continued research and monitoring of emerging trends is recommended."
    )

    conclusion = sections["conclusion"] if sections["conclusion"] else (
        f"In conclusion, {topic} represents a significant and evolving area of interest. "
        f"This research has highlighted key developments, challenges, and opportunities. "
        f"The findings underscore the importance of continued study and engagement with this topic."
    )

    report = f"""---
title: "{topic}"
date: "{date_str}"
generator: "Autonomous Research Agent (LangChain)"
version: "1.0"
---

# {topic}

## Research Report

**Date:** {date_str}
**Generated by:** Autonomous Research Agent
**Powered by:** LangChain + OpenRouter

---

## Introduction

{introduction}

---

## Key Findings

{key_findings}

---

## Challenges

{challenges}

---

## Future Scope

{future_scope}

---

## Conclusion

{conclusion}

---

*This report was automatically generated by the Autonomous Research Agent using LangChain, web search, and Wikipedia knowledge retrieval tools.*
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(report)

    return filepath
